# Builds and deposits artifacts automatically. Based on Fabric's configs


name: Publish Test
on:
  push:
    branches:
      - '**-main'

jobs:
  build:
    name: build artifact
    permissions: write-all
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        id: capture_artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/

      - name: get date/time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}-${{ github.run_attempt }}
          release_name: |
            Build ${{ steps.date.outputs.date }}:${{ github.run_id }}:${{ github.run_attempt }}
          draft: false
          prerelease: false
          body: |
                ### From commit: ${{ github.event.head_commit.message }}
                <sub><sup>Release description automatically generated. Minimal changelogs (if any, really) will be provided for live releases.</sup></sub>
      - name: download artifact
        id: download-artifact
        uses: actions/download-artifact@v3

      - name: push release assets
        id: upload-release-asset 
        uses: csexton/release-asset-action@v2
        with:
          pattern: "build/libs/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}

      - name: notify annoying people
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: beep boop robot man
        uses: Ilshidur/action-discord@master
        with:
          args: |
            <@&1117137065956606083>
            ───────────────────────
            ## New live release available: ``${{ steps.date.outputs.date }}:${{ github.run_id }}:${{ github.run_attempt }}``
            ### Commit details:
            ```
              ${{ github.event.head_commit.message }}
            ```
            **Get it here: https://github.com/quattage/mechano/releases/latest**
            ───────────────────────

